### PR TITLE
Updates for Debian 11 installation

### PR DESCRIPTION
**Pull request by ciscomonkey**
These changes allow installation on Debian 11.

These were tested on Digital Ocean droplets running debian-10-x64 and debian-11-x64 images.

### CODE REVIEW

**Comment by hnimminh** [comment]
thank @ciscomonkey for your contribution to libresbc, very appreciate!

could you separate this to smaller PR, 
1 -  for capagent
1 - for debian

other change like:
*  `"` -> `"`
* `yes` -> `true` 

It is not wrong, let it consistently, and avoid unnecessary/unrelated change.

**Review by hnimminh — CHANGES_REQUESTED** [review]
the change like:
*  `'` -> `"`
* `yes` -> `true` 

It is not wrong, but let it's consistent, and avoid unnecessary/unrelated change. so could you please remove them.

**Comment by ciscomonkey** [comment]
I'll go ahead and close this one out, and submit new ones, as that will be easier.

**Comment by ciscomonkey** [comment]
Side question regarding the single vs double quote, do you have a preference on single quote vs double quote in this project?  The reason that I ask is there is much inconsistency throughout the files here and it wreaks havoc on linters as they always want to change these.

**Pull request closed without merging**
